<?php declare(strict_types=1);

namespace Test\Controller;

use App\Controller\AccountController;
use App\Core\Container;
use App\Core\DependencyProvider;
use App\Core\RedirectRecordings;
use App\Core\View;
use PHPUnit\Framework\TestCase;
use function PHPUnit\Framework\assertInstanceOf;

class AccountControllerTest extends TestCase
{
    public RedirectRecordings $redirectRecordings;

    protected function setUp(): void
    {
        $container = new Container();
        $provider = new DependencyProvider();
        $provider->provide($container);

        $this->redirectRecordings = new RedirectRecordings();

        $this->controller = new AccountController($container);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAction(): void
    {
        session_start();
        $_SESSION["loginStatus"] = true;
        $_SESSION["userID"] = 1;
        $_SESSION["username"] = 'hi';

        $_POST["amount"] = '1';
        $account = $this->controller->action();

        assertInstanceOf(View::class, $account);
    }
}