<?php declare(strict_types=1);

namespace Test\Controller;

use App\Core\DependencyProvider;
use App\Core\RedirectRecordings;
use App\Core\Session;
use App\Model\UserDTO;
use PHPUnit\Framework\TestCase;
use App\Controller\LoginController;
use App\Core\Container;

class LoginControllerTest extends TestCase
{
    public RedirectRecordings $redirectRecordings;
    private Session $session;
    private UserDTO $userDTO;

    protected function setUp(): void
    {
        $container = new Container();
        $provider = new DependencyProvider();
        $provider->provide($container);

        $this->redirectRecordings = new RedirectRecordings();
        $this->session = new Session();

        $this->container = $container;
        $this->controller = new LoginController($this->container);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAction(): void
    {
        $_POST['mail'] = 'Simon@Simon.de';
        $_POST['password'] = 'Simon123#';
        $_POST['login'] = true;

        $this->controller->action();

        self::assertSame('Simon', $this->session->getUserName());
    }

    protected function tearDown(): void
    {
        $this->session->logout();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}