<?php declare(strict_types=1);

namespace Test\Controller;

use App\Controller\TransactionController;
use App\Core\Container;
use App\Core\DependencyProvider;
use App\Core\RedirectRecordings;
use App\Core\View;
use PHPUnit\Framework\TestCase;

class TestTransactionController extends TestCase
{
    public RedirectRecordings $redirectRecordings;

    protected function setUp(): void
    {
        $container = new Container();
        $provider = new DependencyProvider();
        $provider->provide($container);

        $this->redirectRecordings = new RedirectRecordings();

        $this->container = $container;
        $this->controller = new TransactionController($this->container);

        session_start();
        $_SESSION["userID"] = 4;
        $_SESSION["loginStatus"] = true;
        $_SESSION["username"] = "Simon";

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAction(): void
    {
        self::assertContains("Simon", $this->controller->action()->getParameters());
    }
}