<?php declare(strict_types=1);

namespace Test\Controller;

use App\Controller\TransactionController;
use App\Core\Container;
use App\Core\DependencyProvider;
use App\Core\RedirectRecordings;
use App\Core\Session;
use App\Model\SqlConnector;
use App\Model\UserDTO;
use PHPUnit\Framework\TestCase;

class TransactionControllerTest extends TestCase
{
    public RedirectRecordings $redirectRecordings;
    private Session $session;
    private UserDTO $userDTO;

    protected function setUp(): void
    {
        $container = new Container();
        $provider = new DependencyProvider();
        $provider->provide($container);

        $this->redirectRecordings = new RedirectRecordings();
        $this->session = new Session();

        $this->container = $container;
        $this->controller = new TransactionController($this->container);

        $this->userDTO = new UserDTO();
        $this->userDTO->password = '$2y$10$rqTcf57sIEVAZsertDU7P.8O3kObwxc17jL6Cec.6oMcX/VWdFX0i';
        $this->userDTO->username = 'Simon';
        $this->userDTO->email = 'Simon@Simon.de';
        $this->userDTO->userID = 4;
        session_start();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAction(): void
    {
        $this->session->loginUser($this->userDTO, 'Simon123#');
        self::assertContains("Simon", $this->controller->action()->getParameters());
        $this->session->logout();
    }

    public function testActionNoSession(): void
    {
        $this->session->logout();

        $this->controller->action();
        $url = $this->controller->redirect->redirectRecordings->recordedUrl[0];

        self::assertSame($url, 'http://0.0.0.0:8000/?page=login');
    }

    protected function tearDown(): void
    {
        $connector = new SqlConnector();
        $connector->executeDeleteQuery("DELETE FROM Transactions;", []);
        $connector->disconnect();
        $this->session->logout();
        unset($_POST["amount"]);
        unset($this->userDTO);
        unset($this->redirectRecordings);
        unset($this->session);

        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}